
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HolyLogger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string my_callsign {
            get {
                return ((string)(this["my_callsign"]));
            }
            set {
                this["my_callsign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool validation_enabled {
            get {
                return ((bool)(this["validation_enabled"]));
            }
            set {
                this["validation_enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isAllowLiveLog {
            get {
                return ((bool)(this["isAllowLiveLog"]));
            }
            set {
                this["isAllowLiveLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string qrz_username {
            get {
                return ((string)(this["qrz_username"]));
            }
            set {
                this["qrz_username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string qrz_password {
            get {
                return ((string)(this["qrz_password"]));
            }
            set {
                this["qrz_password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string my_square {
            get {
                return ((string)(this["my_square"]));
            }
            set {
                this["my_square"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isLocked {
            get {
                return ((bool)(this["isLocked"]));
            }
            set {
                this["isLocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isManualMode {
            get {
                return ((bool)(this["isManualMode"]));
            }
            set {
                this["isManualMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool isAutoCheckUpdates {
            get {
                return ((bool)(this["isAutoCheckUpdates"]));
            }
            set {
                this["isAutoCheckUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1010")]
        public double MatrixWindowLeft {
            get {
                return ((double)(this["MatrixWindowLeft"]));
            }
            set {
                this["MatrixWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("580")]
        public double MatrixWindowTop {
            get {
                return ((double)(this["MatrixWindowTop"]));
            }
            set {
                this["MatrixWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1010")]
        public double SignBoardWindowLeft {
            get {
                return ((double)(this["SignBoardWindowLeft"]));
            }
            set {
                this["SignBoardWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double SignBoardWindowTop {
            get {
                return ((double)(this["SignBoardWindowTop"]));
            }
            set {
                this["SignBoardWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double MainWindowLeft {
            get {
                return ((double)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double MainWindowTop {
            get {
                return ((double)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1243")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("808")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public double SignBoardWindowWidth {
            get {
                return ((double)(this["SignBoardWindowWidth"]));
            }
            set {
                this["SignBoardWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330")]
        public double SignBoardWindowHeight {
            get {
                return ((double)(this["SignBoardWindowHeight"]));
            }
            set {
                this["SignBoardWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatrixWindowIsOpen {
            get {
                return ((bool)(this["MatrixWindowIsOpen"]));
            }
            set {
                this["MatrixWindowIsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SignBoardWindowIsOpen {
            get {
                return ((bool)(this["SignBoardWindowIsOpen"]));
            }
            set {
                this["SignBoardWindowIsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalInfoCallsign {
            get {
                return ((string)(this["PersonalInfoCallsign"]));
            }
            set {
                this["PersonalInfoCallsign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalInfoName {
            get {
                return ((string)(this["PersonalInfoName"]));
            }
            set {
                this["PersonalInfoName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalInfoEmail {
            get {
                return ((string)(this["PersonalInfoEmail"]));
            }
            set {
                this["PersonalInfoEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalInfoEmailConf {
            get {
                return ((string)(this["PersonalInfoEmailConf"]));
            }
            set {
                this["PersonalInfoEmailConf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool isCommentLocked {
            get {
                return ((bool)(this["isCommentLocked"]));
            }
            set {
                this["isCommentLocked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Date_index {
            get {
                return ((int)(this["Date_index"]));
            }
            set {
                this["Date_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Time_index {
            get {
                return ((int)(this["Time_index"]));
            }
            set {
                this["Time_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Callsign_index {
            get {
                return ((int)(this["Callsign_index"]));
            }
            set {
                this["Callsign_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Name_index {
            get {
                return ((int)(this["Name_index"]));
            }
            set {
                this["Name_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Country_index {
            get {
                return ((int)(this["Country_index"]));
            }
            set {
                this["Country_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int Frequency_index {
            get {
                return ((int)(this["Frequency_index"]));
            }
            set {
                this["Frequency_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int Band_index {
            get {
                return ((int)(this["Band_index"]));
            }
            set {
                this["Band_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int RSTrcvd_index {
            get {
                return ((int)(this["RSTrcvd_index"]));
            }
            set {
                this["RSTrcvd_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int RSTsent_index {
            get {
                return ((int)(this["RSTsent_index"]));
            }
            set {
                this["RSTsent_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Mode_index {
            get {
                return ((int)(this["Mode_index"]));
            }
            set {
                this["Mode_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int Exchange_index {
            get {
                return ((int)(this["Exchange_index"]));
            }
            set {
                this["Exchange_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int Comment_index {
            get {
                return ((int)(this["Comment_index"]));
            }
            set {
                this["Comment_index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double LogUploadWindowLeft {
            get {
                return ((double)(this["LogUploadWindowLeft"]));
            }
            set {
                this["LogUploadWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double LogUploadWindowTop {
            get {
                return ((double)(this["LogUploadWindowTop"]));
            }
            set {
                this["LogUploadWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LogInfoWindowLeft {
            get {
                return ((int)(this["LogInfoWindowLeft"]));
            }
            set {
                this["LogInfoWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int LogInfoWindowTop {
            get {
                return ((int)(this["LogInfoWindowTop"]));
            }
            set {
                this["LogInfoWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RecentQSOCounter {
            get {
                return ((int)(this["RecentQSOCounter"]));
            }
            set {
                this["RecentQSOCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsFilterQSOs {
            get {
                return ((bool)(this["IsFilterQSOs"]));
            }
            set {
                this["IsFilterQSOs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OptionsWindowLeft {
            get {
                return ((double)(this["OptionsWindowLeft"]));
            }
            set {
                this["OptionsWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OptionsWindowTop {
            get {
                return ((double)(this["OptionsWindowTop"]));
            }
            set {
                this["OptionsWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double OptionsWindowWidth {
            get {
                return ((double)(this["OptionsWindowWidth"]));
            }
            set {
                this["OptionsWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("630")]
        public double OptionsWindowHeight {
            get {
                return ((double)(this["OptionsWindowHeight"]));
            }
            set {
                this["OptionsWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowMatrixControl {
            get {
                return ((bool)(this["IsShowMatrixControl"]));
            }
            set {
                this["IsShowMatrixControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableOmniRigCAT {
            get {
                return ((bool)(this["EnableOmniRigCAT"]));
            }
            set {
                this["EnableOmniRigCAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTitleClock {
            get {
                return ((bool)(this["ShowTitleClock"]));
            }
            set {
                this["ShowTitleClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNetworkFlag {
            get {
                return ((bool)(this["ShowNetworkFlag"]));
            }
            set {
                this["ShowNetworkFlag"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPhotoFromQRZ {
            get {
                return ((bool)(this["ShowPhotoFromQRZ"]));
            }
            set {
                this["ShowPhotoFromQRZ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BDDFFF")]
        public string MainFormBackgroundColor {
            get {
                return ((string)(this["MainFormBackgroundColor"]));
            }
            set {
                this["MainFormBackgroundColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DEB887")]
        public string QsoTableHeaderBackgroundColor {
            get {
                return ((string)(this["QsoTableHeaderBackgroundColor"]));
            }
            set {
                this["QsoTableHeaderBackgroundColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF6C8")]
        public string ContestExchangeColor {
            get {
                return ((string)(this["ContestExchangeColor"]));
            }
            set {
                this["ContestExchangeColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E1F5EE")]
        public string ContestSendColor {
            get {
                return ((string)(this["ContestSendColor"]));
            }
            set {
                this["ContestSendColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsParseWARC {
            get {
                return ((bool)(this["IsParseWARC"]));
            }
            set {
                this["IsParseWARC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsParseDuplicates {
            get {
                return ((bool)(this["IsParseDuplicates"]));
            }
            set {
                this["IsParseDuplicates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsSatelliteMode {
            get {
                return ((bool)(this["IsSatelliteMode"]));
            }
            set {
                this["IsSatelliteMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QO-100")]
        public string SatelliteName {
            get {
                return ((string)(this["SatelliteName"]));
            }
            set {
                this["SatelliteName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1968")]
        public double SatelliteShift {
            get {
                return ((double)(this["SatelliteShift"]));
            }
            set {
                this["SatelliteShift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SelectedOmniRig1 {
            get {
                return ((bool)(this["SelectedOmniRig1"]));
            }
            set {
                this["SelectedOmniRig1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectedOmniRig2 {
            get {
                return ((bool)(this["SelectedOmniRig2"]));
            }
            set {
                this["SelectedOmniRig2"] = value;
            }
        }

        // LoTW upload-on-exit mode: 0 = off (never), 1 = ask before uploading, 2 = always upload.
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LotwUploadOnExitMode {
            get {
                return ((int)(this["LotwUploadOnExitMode"]));
            }
            set {
                this["LotwUploadOnExitMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EqslUploadOnExitMode {
            get {
                return ((int)(this["EqslUploadOnExitMode"]));
            }
            set {
                this["EqslUploadOnExitMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QrzUploadOnExitMode {
            get {
                return ((int)(this["QrzUploadOnExitMode"]));
            }
            set {
                this["QrzUploadOnExitMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableUDPClient {
            get {
                return ((bool)(this["EnableUDPClient"]));
            }
            set {
                this["EnableUDPClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2333")]
        public int UDPPort {
            get {
                return ((int)(this["UDPPort"]));
            }
            set {
                this["UDPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string my_locator {
            get {
                return ((string)(this["my_locator"]));
            }
            set {
                this["my_locator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TimerWindowLeft {
            get {
                return ((double)(this["TimerWindowLeft"]));
            }
            set {
                this["TimerWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TimerWindowTop {
            get {
                return ((double)(this["TimerWindowTop"]));
            }
            set {
                this["TimerWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public double TimerWindowWidth {
            get {
                return ((double)(this["TimerWindowWidth"]));
            }
            set {
                this["TimerWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double TimerWindowHeight {
            get {
                return ((double)(this["TimerWindowHeight"]));
            }
            set {
                this["TimerWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimerWindowIsOpen {
            get {
                return ((bool)(this["TimerWindowIsOpen"]));
            }
            set {
                this["TimerWindowIsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayLastQSOinGrid {
            get {
                return ((bool)(this["DisplayLastQSOinGrid"]));
            }
            set {
                this["DisplayLastQSOinGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsShowAzimuthControl {
            get {
                return ((bool)(this["IsShowAzimuthControl"]));
            }
            set {
                this["IsShowAzimuthControl"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MapRadiusKm {
            get {
                return ((int)(this["MapRadiusKm"]));
            }
            set {
                this["MapRadiusKm"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MapUsePolar {
            get {
                return ((bool)(this["MapUsePolar"]));
            }
            set {
                this["MapUsePolar"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MapAutoZoom {
            get {
                return ((bool)(this["MapAutoZoom"]));
            }
            set {
                this["MapAutoZoom"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MapShowDayNight {
            get {
                return ((bool)(this["MapShowDayNight"]));
            }
            set {
                this["MapShowDayNight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Operator {
            get {
                return ((string)(this["Operator"]));
            }
            set {
                this["Operator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddQSOWithEnter {
            get {
                return ((bool)(this["AddQSOWithEnter"]));
            }
            set {
                this["AddQSOWithEnter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNothing {
            get {
                return ((bool)(this["DoNothing"]));
            }
            set {
                this["DoNothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedEvent {
            get {
                return ((string)(this["selectedEvent"]));
            }
            set {
                this["selectedEvent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedMode {
            get {
                return ((string)(this["selectedMode"]));
            }
            set {
                this["selectedMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsOverrideOperator {
            get {
                return ((bool)(this["IsOverrideOperator"]));
            }
            set {
                this["IsOverrideOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.130")]
        public string Frequency {
            get {
                return ((string)(this["Frequency"]));
            }
            set {
                this["Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Comment {
            get {
                return ((string)(this["Comment"]));
            }
            set {
                this["Comment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SSB")]
        public string Mode {
            get {
                return ((string)(this["Mode"]));
            }
            set {
                this["Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDXCCDefaultGrid {
            get {
                return ((bool)(this["UseDXCCDefaultGrid"]));
            }
            set {
                this["UseDXCCDefaultGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableN1MMUDPClient {
            get {
                return ((bool)(this["EnableN1MMUDPClient"]));
            }
            set {
                this["EnableN1MMUDPClient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12060")]
        public int N1MMUDPPort {
            get {
                return ((int)(this["N1MMUDPPort"]));
            }
            set {
                this["N1MMUDPPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedBand {
            get {
                return ((string)(this["selectedBand"]));
            }
            set {
                this["selectedBand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedOperator {
            get {
                return ((string)(this["selectedOperator"]));
            }
            set {
                this["selectedOperator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedPower {
            get {
                return ((string)(this["selectedPower"]));
            }
            set {
                this["selectedPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectedOverlay {
            get {
                return ((string)(this["selectedOverlay"]));
            }
            set {
                this["selectedOverlay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsOverrideOperatorFromFile {
            get {
                return ((bool)(this["IsOverrideOperatorFromFile"]));
            }
            set {
                this["IsOverrideOperatorFromFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int CallsignSuggestionRows {
            get {
                return ((int)(this["CallsignSuggestionRows"]));
            }
            set {
                this["CallsignSuggestionRows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCallsignDropdown {
            get {
                return ((bool)(this["ShowCallsignDropdown"]));
            }
            set {
                this["ShowCallsignDropdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowOnTheAir {
            get {
                return ((bool)(this["ShowOnTheAir"]));
            }
            set {
                this["ShowOnTheAir"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowClusterWindowOption {
            get {
                return ((bool)(this["ShowClusterWindowOption"]));
            }
            set {
                this["ShowClusterWindowOption"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasClosedClusterWindow {
            get {
                return ((bool)(this["HasClosedClusterWindow"]));
            }
            set {
                this["HasClosedClusterWindow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallsignSyncVerboseLog {
            get {
                return ((bool)(this["CallsignSyncVerboseLog"]));
            }
            set {
                this["CallsignSyncVerboseLog"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.15")]
        public double MapAutoFitMargin {
            get {
                return ((double)(this["MapAutoFitMargin"]));
            }
            set {
                this["MapAutoFitMargin"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KM")]
        public string MapDistanceUnit {
            get {
                return ((string)(this["MapDistanceUnit"]));
            }
            set {
                this["MapDistanceUnit"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ClusterWindowLeft {
            get {
                return ((double)(this["ClusterWindowLeft"]));
            }
            set {
                this["ClusterWindowLeft"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double ClusterWindowTop {
            get {
                return ((double)(this["ClusterWindowTop"]));
            }
            set {
                this["ClusterWindowTop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("563")]
        public double ClusterWindowWidth {
            get {
                return ((double)(this["ClusterWindowWidth"]));
            }
            set {
                this["ClusterWindowWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("809")]
        public double ClusterWindowHeight {
            get {
                return ((double)(this["ClusterWindowHeight"]));
            }
            set {
                this["ClusterWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double ColWidthCallsign {
            get {
                return ((double)(this["ColWidthCallsign"]));
            }
            set {
                this["ColWidthCallsign"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double ColWidthName {
            get {
                return ((double)(this["ColWidthName"]));
            }
            set {
                this["ColWidthName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public double ColWidthCountry {
            get {
                return ((double)(this["ColWidthCountry"]));
            }
            set {
                this["ColWidthCountry"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83.546666666666667")]
        public double ClusterColWidthDX {
            get {
                return ((double)(this["ClusterColWidthDX"]));
            }
            set {
                this["ClusterColWidthDX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56.783333333333339")]
        public double ClusterColWidthSpotter {
            get {
                return ((double)(this["ClusterColWidthSpotter"]));
            }
            set {
                this["ClusterColWidthSpotter"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("58.860000000000007")]
        public double ClusterColWidthFreq {
            get {
                return ((double)(this["ClusterColWidthFreq"]));
            }
            set {
                this["ClusterColWidthFreq"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44")]
        public double ClusterColWidthUtc {
            get {
                return ((double)(this["ClusterColWidthUtc"]));
            }
            set {
                this["ClusterColWidthUtc"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95.496666666666329")]
        public double ClusterColWidthComment {
            get {
                return ((double)(this["ClusterColWidthComment"]));
            }
            set {
                this["ClusterColWidthComment"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44.74666666666667")]
        public double ClusterColWidthMode {
            get {
                return ((double)(this["ClusterColWidthMode"]));
            }
            set {
                this["ClusterColWidthMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public double ClusterSettingsWindowLeft {
            get {
                return ((double)(this["ClusterSettingsWindowLeft"]));
            }
            set {
                this["ClusterSettingsWindowLeft"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public double ClusterSettingsWindowTop {
            get {
                return ((double)(this["ClusterSettingsWindowTop"]));
            }
            set {
                this["ClusterSettingsWindowTop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("380")]
        public double ClusterSettingsWindowWidth {
            get {
                return ((double)(this["ClusterSettingsWindowWidth"]));
            }
            set {
                this["ClusterSettingsWindowWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("260")]
        public double ClusterSettingsWindowHeight {
            get {
                return ((double)(this["ClusterSettingsWindowHeight"]));
            }
            set {
                this["ClusterSettingsWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160,80,60,40,30,20,17,15,12,10,6,VHF,UHF,SHF")]
        public string ClusterEnabledBands {
            get {
                return ((string)(this["ClusterEnabledBands"]));
            }
            set {
                this["ClusterEnabledBands"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ClusterUseActiveBand {
            get {
                return ((bool)(this["ClusterUseActiveBand"]));
            }
            set {
                this["ClusterUseActiveBand"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PreSelected")]
        public string ClusterBandFilterMode {
            get {
                return ((string)(this["ClusterBandFilterMode"]));
            }
            set {
                this["ClusterBandFilterMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PreSelected")]
        public string ClusterPreferredBandMode {
            get {
                return ((string)(this["ClusterPreferredBandMode"]));
            }
            set {
                this["ClusterPreferredBandMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CW,DIGI,SSB,FM,FT8,RTTY,AM")]
        public string ClusterEnabledModes {
            get {
                return ((string)(this["ClusterEnabledModes"]));
            }
            set {
                this["ClusterEnabledModes"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClusterBandColors {
            get {
                return ((string)(this["ClusterBandColors"]));
            }
            set {
                this["ClusterBandColors"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClusterMapEnabled {
            get {
                return ((bool)(this["ClusterMapEnabled"]));
            }
            set {
                this["ClusterMapEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClusterActive {
            get {
                return ((bool)(this["ClusterActive"]));
            }
            set {
                this["ClusterActive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallsignSuggestionsEnabled {
            get {
                return ((bool)(this["CallsignSuggestionsEnabled"]));
            }
            set {
                this["CallsignSuggestionsEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EqslAutoUpload {
            get {
                return ((bool)(this["EqslAutoUpload"]));
            }
            set {
                this["EqslAutoUpload"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EqslUsername {
            get {
                return ((string)(this["EqslUsername"]));
            }
            set {
                this["EqslUsername"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EqslPassword {
            get {
                return ((string)(this["EqslPassword"]));
            }
            set {
                this["EqslPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EqslQthNickname {
            get {
                return ((string)(this["EqslQthNickname"]));
            }
            set {
                this["EqslQthNickname"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContestMode {
            get {
                return ((bool)(this["ContestMode"]));
            }
            set {
                this["ContestMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContestName {
            get {
                return ((string)(this["ContestName"]));
            }
            set {
                this["ContestName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveContestId {
            get {
                return ((string)(this["ActiveContestId"]));
            }
            set {
                this["ActiveContestId"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CQ CQ DE K")]
        public string CwMsgText1 {
            get {
                return ((string)(this["CwMsgText1"]));
            }
            set {
                this["CwMsgText1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DE K")]
        public string CwMsgText2 {
            get {
                return ((string)(this["CwMsgText2"]));
            }
            set {
                this["CwMsgText2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TU 73")]
        public string CwMsgText3 {
            get {
                return ((string)(this["CwMsgText3"]));
            }
            set {
                this["CwMsgText3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NR?")]
        public string CwMsgText4 {
            get {
                return ((string)(this["CwMsgText4"]));
            }
            set {
                this["CwMsgText4"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MapAreaDisplayMode {
            get {
                return ((int)(this["MapAreaDisplayMode"]));
            }
            set {
                this["MapAreaDisplayMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomMapImagePath {
            get {
                return ((string)(this["CustomMapImagePath"]));
            }
            set {
                this["CustomMapImagePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double SearchWindowLeft {
            get {
                return ((double)(this["SearchWindowLeft"]));
            }
            set {
                this["SearchWindowLeft"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double SearchWindowTop {
            get {
                return ((double)(this["SearchWindowTop"]));
            }
            set {
                this["SearchWindowTop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1133")]
        public double SearchWindowWidth {
            get {
                return ((double)(this["SearchWindowWidth"]));
            }
            set {
                this["SearchWindowWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("644")]
        public double SearchWindowHeight {
            get {
                return ((double)(this["SearchWindowHeight"]));
            }
            set {
                this["SearchWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double StatisticsWindowLeft {
            get {
                return ((double)(this["StatisticsWindowLeft"]));
            }
            set {
                this["StatisticsWindowLeft"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double StatisticsWindowTop {
            get {
                return ((double)(this["StatisticsWindowTop"]));
            }
            set {
                this["StatisticsWindowTop"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double StatisticsWindowWidth {
            get {
                return ((double)(this["StatisticsWindowWidth"]));
            }
            set {
                this["StatisticsWindowWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double StatisticsWindowHeight {
            get {
                return ((double)(this["StatisticsWindowHeight"]));
            }
            set {
                this["StatisticsWindowHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string qrz_api_key {
            get {
                return ((string)(this["qrz_api_key"]));
            }
            set {
                this["qrz_api_key"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qrz_logbook_auto_push {
            get {
                return ((bool)(this["qrz_logbook_auto_push"]));
            }
            set {
                this["qrz_logbook_auto_push"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool qrz_logbook_key_valid {
            get {
                return ((bool)(this["qrz_logbook_key_valid"]));
            }
            set {
                this["qrz_logbook_key_valid"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Trusted QSL\\tqsl.exe")]
        public string LotwTqslPath {
            get {
                return ((string)(this["LotwTqslPath"]));
            }
            set {
                this["LotwTqslPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LotwStationLocation {
            get {
                return ((string)(this["LotwStationLocation"]));
            }
            set {
                this["LotwStationLocation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LotwCallsignLocations {
            get {
                return ((string)(this["LotwCallsignLocations"]));
            }
            set {
                this["LotwCallsignLocations"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LotwTqslPassword {
            get {
                return ((string)(this["LotwTqslPassword"]));
            }
            set {
                this["LotwTqslPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LotwWebUser {
            get {
                return ((string)(this["LotwWebUser"]));
            }
            set {
                this["LotwWebUser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LotwWebPassword {
            get {
                return ((string)(this["LotwWebPassword"]));
            }
            set {
                this["LotwWebPassword"] = value;
            }
        }
    }
}
